# Generated by Django 2.1 on 2018-08-28 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('optinal', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=200)),
                ('answerType', models.CharField(max_length=200)),
                ('after', models.ManyToManyField(default=None, related_name='_question_after_+', to='questions.Question')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Category')),
            ],
        ),
    ]
