# Generated by Django 2.1 on 2018-08-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='after',
            field=models.ManyToManyField(default=None, null=True, related_name='_question_after_+', to='questions.Question'),
        ),
    ]
