# Generated by Django 2.1 on 2018-08-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180828_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='after',
            field=models.ManyToManyField(blank=True, null=True, related_name='_question_after_+', to='questions.Question'),
        ),
    ]
