# Generated by Django 2.1 on 2018-08-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180828_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('answer_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=600)),
                ('question_id', models.ForeignKey(on_delete=None, to='questions.Question')),
            ],
        ),
    ]
