# Generated by Django 2.1 on 2018-08-31 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
