# Generated by Django 2.1 on 2018-08-31 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20180831_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
