# Generated by Django 2.1 on 2018-08-31 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_question_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
