# Generated by Django 2.1 on 2018-08-31 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_question_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='after',
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('711388b5-942b-433b-bc2f-0aa6e5fa0011'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('27629c25-ce52-4ffb-9ca9-1d8408034f04'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
