# Generated by Django 2.1 on 2018-08-31 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20180831_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('04e1ecac-e1b2-4b88-be71-9cf47b087628'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('968b0c9b-39ab-4d20-a222-fcf731a9f4ef'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
