# Generated by Django 2.1 on 2018-09-05 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20180831_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('d36e3850-25bf-4d44-a4a5-ddfc79d840c4'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('1f5488aa-e1b0-485c-9076-1fa601175245'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
