# Generated by Django 2.1 on 2018-09-05 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20180905_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('3bdf97b4-448d-466c-aecf-2508d8fb132b'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('20061d36-4926-41bf-b9df-42c48f5c589a'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
