# Generated by Django 2.1 on 2018-09-05 22:31

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20180905_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('850bcf33-6fac-4ff1-bdd0-9d5219cf573d'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('72a2bf5a-b16a-4114-9405-c57b776c786f'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
