# Generated by Django 2.1 on 2018-09-05 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20180905_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('2c36b78e-e945-4238-a905-9ea79f09daf0'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('42d24337-96a0-4ba3-a8d8-01e3b027b992'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
