# Generated by Django 2.1 on 2018-09-05 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20180905_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('18e7f514-0197-4df4-a2d5-d568acac24d0'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('27c9195c-10b1-4796-b01c-c18cd422f9db'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
