# Generated by Django 2.1 on 2018-09-06 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20180905_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('3f790f59-007c-4b09-b5a1-869b16892a1f'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('dceb3e2e-b8cb-41c4-9c70-5c1bbd068d16'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
