# Generated by Django 2.1 on 2018-09-06 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20180906_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('b0d2b364-c216-4727-bce3-819bae6c28f9'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('91512a0f-f664-4fcf-b44e-b1f670dbde2f'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
