# Generated by Django 2.1 on 2018-09-06 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20180906_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('f9605668-ca5f-427b-90d1-ebb411a89358'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('455380e6-77c3-498a-8fd4-5fb36a568f77'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
