# Generated by Django 2.1 on 2018-09-06 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20180906_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('82ea4877-b7c1-4550-a6cd-7696d3d9b811'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('ffbef8aa-0d5b-4398-ae39-c5f6a8514779'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
