# Generated by Django 2.1 on 2018-09-07 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20180906_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('b5bdbb43-77b4-4a9b-bec9-1dbcfa6f97b8'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('fcc02be1-d0db-4966-8109-a9c5124f9a6a'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
