# Generated by Django 2.1 on 2018-09-08 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20180907_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('f9d1bb1f-de39-49df-9911-720fab8ed424'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('1974f432-cf09-4066-b0d8-d984fa709699'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
