# Generated by Django 2.1 on 2018-09-10 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20180908_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('28b10376-505c-449d-9e17-58ead1fdbbba'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('e3806fa1-688b-476b-a94e-e5b96c8bbf1b'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
