# Generated by Django 2.1 on 2018-09-11 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20180910_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('bbf22760-c422-48a3-9fa0-ef5dec75fc89'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('56a66275-c265-4cb4-8ace-8c0269680471'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
