# Generated by Django 2.1 on 2018-09-11 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20180911_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='className',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('0c19a205-bb5a-4cd8-a9bd-117a592e6394'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('96c523dd-6c50-4d39-b543-bdd89b58334b'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
