# Generated by Django 2.1 on 2018-09-12 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_auto_20180911_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('7b5bc59e-ccb5-4167-8c89-36533802238e'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('a07bb593-1794-4b6f-9e35-22fa661470a5'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
