# Generated by Django 2.1 on 2018-09-12 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20180912_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('cef082e0-d758-4a0d-9b01-f0cc38992faf'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('e49b8e62-8c7e-4648-95bb-7fa9bac6aa40'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
