# Generated by Django 2.1 on 2018-09-12 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20180912_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('f3f1ef9f-c8bd-4da8-8b46-4a3e90e18d5c'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('85e0bd3d-29bf-4f25-83dd-1ddd5f072f04'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
