# Generated by Django 2.1 on 2018-09-14 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_auto_20180912_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('ecc240a3-2281-4c9f-a55b-d984b522c800'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('34d0cdea-b5b4-4ac4-9945-5b7658dcbde2'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
