# Generated by Django 2.1 on 2018-09-14 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_auto_20180914_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='after',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('a376e889-59fd-4295-ace3-0d77b1741f23'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=uuid.UUID('34a018a4-4ce2-445e-b671-601bfe6cfdf4'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
