# Generated by Django 2.1 on 2018-09-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20180905_1953'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_category', models.IntegerField()),
                ('index_question', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=None, to='chats.User')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.OneToOneField(default=0, on_delete=None, to='questions.Question'),
            preserve_default=False,
        ),
    ]
