# Generated by Django 2.1 on 2018-09-05 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20180905_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('20e05bdc-c1eb-4978-9ca9-408938d0fdd2'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
