# Generated by Django 2.1 on 2018-09-05 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20180905_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('b694a1a7-dbf8-425d-a816-3c02038ace9e'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
