# Generated by Django 2.1 on 2018-09-05 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20180905_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('71800501-80c1-43e2-989b-fba646abb3e8'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=None, to='chats.User'),
        ),
    ]
