# Generated by Django 2.1 on 2018-09-06 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_auto_20180905_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('36eb867b-c6fe-4387-b1d6-ecb2413efe3d'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
