# Generated by Django 2.1 on 2018-09-06 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20180906_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('ada299db-df6a-4655-b179-4b5fcc705f06'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=None, to='questions.Question'),
        ),
    ]
