# Generated by Django 2.1 on 2018-09-06 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20180906_0023'),
        ('chats', '0008_auto_20180906_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('0f95ac02-621a-4470-b85b-ae156b40e3d4'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ManyToManyField(to='questions.Question'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ManyToManyField(to='chats.User'),
        ),
    ]
