# Generated by Django 2.1 on 2018-09-06 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20180906_0025'),
        ('chats', '0009_auto_20180906_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('c7ef5116-48aa-4029-9e02-0f48f02be82c'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=0, on_delete=None, to='questions.Question'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=None, to='chats.User'),
        ),
    ]
