# Generated by Django 2.1 on 2018-09-07 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_auto_20180906_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('414031cd-c93b-4335-893a-5ecb54af87be'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
