# Generated by Django 2.1 on 2018-09-11 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_auto_20180911_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch_reasons',
            fields=[
                ('reason', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('0782b94a-7b97-4b8d-a73b-260e5e825a30'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='switch_reasons',
            field=models.ManyToManyField(to='chats.Switch_reasons'),
        ),
    ]
