# Generated by Django 2.1 on 2018-09-12 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_auto_20180911_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('43e7f06e-bf67-4ed2-b5c9-03ddf1f80c70'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='employed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
