# Generated by Django 2.1 on 2018-09-12 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_auto_20180912_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('c8a18eca-cc03-4780-b6db-98bb7195bd5c'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
