# Generated by Django 2.1 on 2018-09-12 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_auto_20180912_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('5e6bfa89-1a4c-44ff-b86e-37eaf4934d48'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.CharField(default='2018', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gross_salary',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_of_experience',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
