# Generated by Django 2.1 on 2018-09-14 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_auto_20180912_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('64436baf-b0c3-4cde-b93f-e7edc1c4ea4e'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='user',
            name='seeking_titles',
        ),
        migrations.AddField(
            model_name='user',
            name='seeking_titles',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='switch_reasons',
        ),
        migrations.AddField(
            model_name='user',
            name='switch_reasons',
            field=models.TextField(null=True),
        ),
    ]
