# Generated by Django 2.1 on 2018-09-14 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_auto_20180914_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('0892dd6c-fdb2-4f67-9dec-12532a5ec4ce'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
