# Generated by Django 2.1 on 2018-09-14 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0020_auto_20180914_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('93f0b746-1ec2-433e-9e68-61dbcc7ba52c'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
