# Generated by Django 2.1 on 2018-09-16 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0021_auto_20180914_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employement_field',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='soft_skills',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tech_skills',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default=uuid.UUID('766f4ee7-98ec-4b05-9af7-49593b434b09'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
